import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { CandidateLocation, RawScores, Weights } from '@/lib/analysis'

export interface PDFExportData {
  locationName: string
  finalScore: number
  rationale: string
  weights: Weights
  rawScores?: RawScores
  estimatedFamilies: string
  medianIncome: string
  competition: string
  mapElement?: HTMLElement
  radarElement?: HTMLElement
}

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[^a-z0-9]+/gi, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
    .toLowerCase()
}

function setDocumentFont(
  pdf: jsPDF,
  style: 'normal' | 'bold' | 'italic' | 'bolditalic' = 'normal'
): void {
  pdf.setFont('times', style)
}

function addFooter(pdf: jsPDF): void {
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const footerY = pageHeight - 15

  pdf.setFontSize(8)
  setDocumentFont(pdf, 'italic')
  pdf.setTextColor(107, 114, 128)
  pdf.text('Generated by theCoderSchool Market Lens', pageWidth / 2, footerY, { align: 'center' })
  pdf.text(new Date().toLocaleDateString(), pageWidth / 2, footerY + 5, { align: 'center' })
}

function addSectionTitle(pdf: jsPDF, title: string, x: number, y: number, lineWidth: number): void {
  pdf.setFontSize(14)
  setDocumentFont(pdf, 'bold')
  pdf.setTextColor(31, 41, 55)
  pdf.text(title, x, y)
  pdf.setDrawColor(148, 163, 184)
  pdf.setLineWidth(0.35)
  pdf.line(x, y + 2.5, x + lineWidth, y + 2.5)
}

export async function generateInvestmentBrief(data: PDFExportData): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 18
  const contentWidth = pageWidth - marginX * 2
  let yPosition = 22

  pdf.setDrawColor(71, 85, 105)
  pdf.setLineWidth(0.45)
  pdf.rect(12, 12, pageWidth - 24, pageHeight - 24)
  pdf.line(marginX, 34, pageWidth - marginX, 34)

  pdf.setFontSize(11)
  setDocumentFont(pdf, 'normal')
  pdf.setTextColor(75, 85, 99)
  pdf.text('theCoderSchool Market Lens', marginX, yPosition)

  pdf.setFontSize(24)
  setDocumentFont(pdf, 'bold')
  pdf.setTextColor(17, 24, 39)
  pdf.text('Investment Opportunity Brief', marginX, yPosition + 10)

  pdf.setFontSize(10)
  setDocumentFont(pdf, 'italic')
  pdf.setTextColor(100, 116, 139)
  pdf.text(new Date().toLocaleDateString(), pageWidth - marginX, yPosition, { align: 'right' })
  yPosition = 48

  pdf.setFontSize(18)
  setDocumentFont(pdf, 'bold')
  pdf.setTextColor(17, 24, 39)
  pdf.text(data.locationName, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 10

  pdf.setFontSize(12)
  setDocumentFont(pdf, 'normal')
  pdf.setTextColor(55, 65, 81)
  pdf.text(`Final Score: ${data.finalScore}/100`, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 16

  pdf.setDrawColor(203, 213, 225)
  pdf.setFillColor(248, 250, 252)
  pdf.roundedRect(marginX, yPosition, contentWidth, 36, 2, 2, 'FD')

  addSectionTitle(pdf, 'Key Metrics', marginX + 4, yPosition + 8, 32)

  setDocumentFont(pdf, 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(55, 65, 81)
  const metrics = [
    `Estimated Families: ${data.estimatedFamilies}`,
    `Median Income: ${data.medianIncome}`,
    `Competition Level: ${data.competition}`
  ]

  const metricY = yPosition + 20
  metrics.forEach((metric, index) => {
    pdf.text(metric, marginX + 6, metricY + index * 6)
  })
  yPosition += 48

  addSectionTitle(pdf, 'Analysis Rationale', marginX, yPosition, 42)
  yPosition += 10

  setDocumentFont(pdf, 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(55, 65, 81)
  const rationaleLines = pdf.splitTextToSize(data.rationale, contentWidth)
  pdf.text(rationaleLines, marginX, yPosition)
  yPosition += rationaleLines.length * 5 + 18

  if (yPosition > pageHeight - 60) {
    pdf.addPage()
    pdf.setDrawColor(71, 85, 105)
    pdf.setLineWidth(0.45)
    pdf.rect(12, 12, pageWidth - 24, pageHeight - 24)
    yPosition = 20
  }

  addSectionTitle(pdf, 'Strategy Configuration', marginX, yPosition, 46)
  yPosition += 10

  pdf.setDrawColor(203, 213, 225)
  pdf.setFillColor(249, 250, 251)
  pdf.roundedRect(marginX, yPosition - 2, contentWidth, 40, 2, 2, 'FD')

  setDocumentFont(pdf, 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(55, 65, 81)
  const weightLabels = ['Wealth', 'Family', 'Education', 'Competition', 'Accessibility']
  const weightKeys: (keyof typeof data.weights)[] = ['wealth', 'family', 'education', 'competition', 'accessibility']

  weightKeys.forEach((key, index) => {
    const weight = Math.round(data.weights[key] * 100)
    const rawScore = data.rawScores?.[key]
    const contribution = rawScore ? Math.round(weight * rawScore / 100 * 100) / 100 : 'N/A'
    pdf.text(
      `${weightLabels[index]}: ${weight}% ${rawScore ? `(Score: ${rawScore}/100, Contribution: ${contribution} pts)` : ''}`,
      marginX + 6,
      yPosition + index * 6.2
    )
  })
  yPosition += 44

  addFooter(pdf)

  // Download the PDF
  pdf.save(`${sanitizeFilenamePart(data.locationName)}_score_breakdown.pdf`)
}

export async function generateComparisonBrief(locations: CandidateLocation[], title = 'Location Comparison'): Promise<void> {
  const comparableLocations = locations.filter((location) => location.rawScores)
  if (comparableLocations.length === 0) return

  const pdf = new jsPDF('l', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 16
  let yPosition = 18
  const weightKeys: Array<keyof RawScores> = ['wealth', 'family', 'education', 'competition', 'accessibility']
  const weightLabels: Record<keyof RawScores, string> = {
    wealth: 'Wealth',
    family: 'Family',
    education: 'Education',
    competition: 'Competition',
    accessibility: 'Accessibility',
  }

  pdf.setDrawColor(71, 85, 105)
  pdf.setLineWidth(0.45)
  pdf.rect(12, 12, pageWidth - 24, pageHeight - 24)
  pdf.line(marginX, 30, pageWidth - marginX, 30)

  pdf.setTextColor(75, 85, 99)
  pdf.setFontSize(11)
  setDocumentFont(pdf, 'normal')
  pdf.text('theCoderSchool Market Lens', marginX, yPosition)
  yPosition += 9
  pdf.setTextColor(17, 24, 39)
  pdf.setFontSize(20)
  setDocumentFont(pdf, 'bold')
  pdf.text(title, marginX, yPosition)
  yPosition += 14

  const factorColWidth = 42
  const valueColWidth = (pageWidth - 20 - factorColWidth) / comparableLocations.length

  pdf.setFillColor(243, 244, 246)
  pdf.setDrawColor(203, 213, 225)
  pdf.rect(10, yPosition, pageWidth - 20, 12, 'FD')
  pdf.setFontSize(10)
  setDocumentFont(pdf, 'bold')
  pdf.setTextColor(31, 41, 55)
  pdf.text('Factor', 14, yPosition + 8)
  comparableLocations.forEach((location, index) => {
    const x = 10 + factorColWidth + index * valueColWidth
    const shortName = location.name.replace(/,\s*/g, ' ').slice(0, 26)
    pdf.text(shortName, x + 4, yPosition + 5)
    setDocumentFont(pdf, 'normal')
    pdf.text(`Score: ${location.score}/100`, x + 4, yPosition + 9)
    setDocumentFont(pdf, 'bold')
  })
  yPosition += 12

  const rows = [
    { label: 'Estimated Families', values: comparableLocations.map((location) => location.estimatedFamilies) },
    { label: 'Median Income', values: comparableLocations.map((location) => location.medianIncome) },
    { label: 'Competition', values: comparableLocations.map((location) => location.competition) },
    ...weightKeys.map((key) => ({
      label: weightLabels[key],
      values: comparableLocations.map((location) => `${location.rawScores?.[key].toFixed(1) ?? '0.0'}`),
    })),
  ]

  rows.forEach((row, rowIndex) => {
    const rowHeight = 10
    pdf.setFillColor(rowIndex % 2 === 0 ? 255 : 249, rowIndex % 2 === 0 ? 255 : 250, rowIndex % 2 === 0 ? 255 : 251)
    pdf.rect(10, yPosition, pageWidth - 20, rowHeight, 'F')
    pdf.setDrawColor(226, 232, 240)
    pdf.rect(10, yPosition, pageWidth - 20, rowHeight)
    pdf.setTextColor(31, 41, 55)
    setDocumentFont(pdf, 'bold')
    pdf.text(row.label, 14, yPosition + 6.5)
    setDocumentFont(pdf, 'normal')

    row.values.forEach((value, index) => {
      const x = 10 + factorColWidth + index * valueColWidth
      pdf.text(String(value), x + 4, yPosition + 6.5)
    })

    yPosition += rowHeight
  })

  yPosition += 8
  setDocumentFont(pdf, 'bold')
  pdf.setFontSize(12)
  pdf.setTextColor(31, 41, 55)
  pdf.text('Rationales', 15, yPosition)
  yPosition += 8
  setDocumentFont(pdf, 'normal')
  pdf.setFontSize(10)
  pdf.setTextColor(55, 65, 81)

  comparableLocations.forEach((location, index) => {
    const rationaleLines = pdf.splitTextToSize(
      `${index + 1}. ${location.name}: ${location.rationale}`,
      pageWidth - 30
    )
    if (yPosition + rationaleLines.length * 4 > 190) {
      addFooter(pdf)
      pdf.addPage()
      yPosition = 20
    }
    pdf.text(rationaleLines, 15, yPosition)
    yPosition += rationaleLines.length * 4 + 4
  })

  addFooter(pdf)
  pdf.save(`${sanitizeFilenamePart(title)}.pdf`)
}
