import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { CandidateLocation, RawScores, Weights } from '@/lib/analysis'

export interface PDFExportData {
  locationName: string
  finalScore: number
  rationale: string
  weights: Weights
  rawScores?: RawScores
  estimatedFamilies: string
  medianIncome: string
  competition: string
  mapElement?: HTMLElement
  radarElement?: HTMLElement
}

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[^a-z0-9]+/gi, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
    .toLowerCase()
}

function generateRadarSVG(weights: PDFExportData['weights']): string {
  const size = 200
  const cx = size / 2
  const cy = size / 2
  const radius = 80

  const weightValues = [weights.wealth, weights.family, weights.education, weights.competition, weights.accessibility]
  // Updated to an emerald-focused, cohesive color palette
  const colors = ['#065f46', '#10b981', '#f59e0b', '#ef4444', '#0f766e']

  let svg = `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">`

  // Background circles
  ;[0.25, 0.5, 0.75, 1].forEach(level => {
    const r = radius * level
    const points = Array.from({ length: 5 }).map((_, i) => {
      const angle = -Math.PI / 2 + (Math.PI * 2 * i) / 5
      const x = cx + Math.cos(angle) * r
      const y = cy + Math.sin(angle) * r
      return `${x},${y}`
    }).join(' ')
    svg += `<polygon points="${points}" fill="none" stroke="#e2e8f0" stroke-width="1"/>`
  })

  // Axis lines
  Array.from({ length: 5 }).forEach((_, i) => {
    const angle = -Math.PI / 2 + (Math.PI * 2 * i) / 5
    const x = cx + Math.cos(angle) * radius
    const y = cy + Math.sin(angle) * radius
    svg += `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#e2e8f0" stroke-width="1"/>`
  })

  // Radar shape (Updated to Emerald)
  const radarPoints = weightValues.map((value, i) => {
    const angle = -Math.PI / 2 + (Math.PI * 2 * i) / 5
    const x = cx + Math.cos(angle) * radius * value
    const y = cy + Math.sin(angle) * radius * value
    return `${x},${y}`
  }).join(' ')

  // fill: emerald-500 (20% opacity), stroke: emerald-600
  svg += `<polygon points="${radarPoints}" fill="rgba(16, 185, 129, 0.2)" stroke="#059669" stroke-width="2"/>`

  // Data points and lines
  weightValues.forEach((value, i) => {
    const angle = -Math.PI / 2 + (Math.PI * 2 * i) / 5
    const x = cx + Math.cos(angle) * radius * value
    const y = cy + Math.sin(angle) * radius * value
    const outerX = cx + Math.cos(angle) * radius
    const outerY = cy + Math.sin(angle) * radius

    svg += `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="${colors[i]}" stroke-width="2" stroke-linecap="round"/>`
    svg += `<circle cx="${x}" cy="${y}" r="4" fill="${colors[i]}"/>`
    svg += `<circle cx="${outerX}" cy="${outerY}" r="2" fill="${colors[i]}" opacity="0.45"/>`
  })

  svg += '</svg>'
  return svg
}

async function addRadarChartToPDF(pdf: jsPDF, weights: PDFExportData['weights'], x: number, y: number): Promise<void> {
  try {
    const radarSvg = generateRadarSVG(weights)
    const canvas = document.createElement('canvas')
    canvas.width = 200
    canvas.height = 200
    const ctx = canvas.getContext('2d')

    if (ctx) {
      const img = new Image()
      const svgBlob = new Blob([radarSvg], { type: 'image/svg+xml' })
      const url = URL.createObjectURL(svgBlob)

      await new Promise<void>((resolve) => {
        img.onload = () => {
          ctx.drawImage(img, 0, 0)
          URL.revokeObjectURL(url)
          resolve()
        }
        img.src = url
      })

      const imgData = canvas.toDataURL('image/png')
      pdf.addImage(imgData, 'PNG', x, y, 60, 60)
    }
  } catch (error) {
    console.error('Failed to generate radar chart:', error)
    // Fallback: just add text
    pdf.setFont('helvetica', 'italic')
    pdf.setFontSize(10)
    pdf.text('Strategy visualization not available', x, y + 30)
  }
}

function addFooter(pdf: jsPDF): void {
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const footerY = pageHeight - 15

  pdf.setFontSize(8)
  pdf.setFont('helvetica', 'italic')
  pdf.setTextColor(100, 116, 139)
  pdf.text('Generated by theCoderSchool Market Lens', pageWidth / 2, footerY, { align: 'center' })
  pdf.text(new Date().toLocaleDateString(), pageWidth / 2, footerY + 5, { align: 'center' })
}

function addSectionTitle(pdf: jsPDF, title: string, x: number, y: number, lineWidth: number): void {
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(15, 23, 42)
  pdf.text(title, x, y)
  pdf.setDrawColor(6, 95, 70)
  pdf.setLineWidth(0.5)
  pdf.line(x, y + 2, x + lineWidth, y + 2)
}

function addMapUnavailableCard(pdf: jsPDF, x: number, y: number, width: number, height: number, locationName: string): void {
  pdf.setFillColor(248, 250, 252)
  pdf.setDrawColor(203, 213, 225)
  pdf.roundedRect(x, y, width, height, 3, 3, 'FD')
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(12)
  pdf.setTextColor(15, 23, 42)
  pdf.text(locationName, x + 6, y + 12)
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(10)
  pdf.setTextColor(100, 116, 139)
  const lines = pdf.splitTextToSize(
    'Map preview was unavailable during export, but this brief still reserves the location overview section.',
    width - 12
  )
  pdf.text(lines, x + 6, y + 22)
}

export async function generateInvestmentBrief(data: PDFExportData): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  let yPosition = 20

  // Header box (Updated to Emerald Theme)
  pdf.setFillColor(236, 253, 245) // emerald-50
  pdf.rect(10, 10, pageWidth - 20, 50, 'F')
  pdf.setDrawColor(6, 95, 70) // emerald-800 border
  pdf.setLineWidth(1)
  pdf.rect(10, 10, pageWidth - 20, 50)

  // Header with branding
  pdf.setFontSize(28)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(6, 95, 70) // emerald-800 text
  pdf.text('theCoderSchool Market Lens', pageWidth / 2, yPosition + 5, { align: 'center' })
  yPosition += 8

  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(15, 23, 42) // slate-900
  pdf.text('Investment Opportunity Brief', pageWidth / 2, yPosition + 5, { align: 'center' })
  yPosition += 25

  // Location and Score
  pdf.setFontSize(18)
  pdf.setFont('helvetica', 'bold')
  pdf.text(data.locationName, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 10

  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Final Score: ${data.finalScore}/100`, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 20

  // Key Metrics Section
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(15, 23, 42)
  pdf.text('Key Metrics', 20, yPosition)
  pdf.setDrawColor(6, 95, 70)
  pdf.setLineWidth(0.5)
  pdf.line(20, yPosition + 2, 80, yPosition + 2)
  yPosition += 10

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  const metrics = [
    `Estimated Families: ${data.estimatedFamilies}`,
    `Median Income: ${data.medianIncome}`,
    `Competition Level: ${data.competition}`
  ]

  metrics.forEach(metric => {
    pdf.text(metric, 25, yPosition)
    yPosition += 6
  })
  yPosition += 15

  // Rationale Section
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Analysis Rationale', 20, yPosition)
  pdf.line(20, yPosition + 2, 90, yPosition + 2)
  yPosition += 10

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  const rationaleLines = pdf.splitTextToSize(data.rationale, pageWidth - 40)
  pdf.text(rationaleLines, 20, yPosition)
  yPosition += rationaleLines.length * 5 + 15

  // Weights Breakdown Section
  if (yPosition > pageHeight - 60) {
    pdf.addPage()
    yPosition = 20
  }

  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Strategy Configuration', 20, yPosition)
  pdf.line(20, yPosition + 2, 100, yPosition + 2)
  yPosition += 10

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  const weightLabels = ['Wealth', 'Family', 'Education', 'Competition', 'Accessibility']
  const weightKeys: (keyof typeof data.weights)[] = ['wealth', 'family', 'education', 'competition', 'accessibility']

  weightKeys.forEach((key, index) => {
    const weight = Math.round(data.weights[key] * 100)
    const rawScore = data.rawScores?.[key]
    const contribution = rawScore ? Math.round(weight * rawScore / 100 * 100) / 100 : 'N/A'
    pdf.text(`${weightLabels[index]}: ${weight}% ${rawScore ? `(Score: ${rawScore}/100, Contribution: ${contribution} pts)` : ''}`, 25, yPosition)
    yPosition += 6
  })
  yPosition += 20

  // Add Radar Chart
  if (yPosition > pageHeight - 90) {
    pdf.addPage()
    yPosition = 20
  }

  addSectionTitle(pdf, 'Strategy Visualization', 20, yPosition, 85)
  yPosition += 10
  await addRadarChartToPDF(pdf, data.weights, 20, yPosition)
  yPosition += 70

  // Capture and add map section regardless of remaining space
  if (yPosition > pageHeight - 90) {
    pdf.addPage()
    yPosition = 20
  }

  addSectionTitle(pdf, 'Location Overview', 20, yPosition, 65)
  yPosition += 8

  if (data.mapElement) {
    try {
      const mapCanvas = await html2canvas(data.mapElement, {
        scale: 1,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff'
      })

      const imgData = mapCanvas.toDataURL('image/png')
      const imgWidth = 80
      const imgHeight = (mapCanvas.height * imgWidth) / mapCanvas.width

      if (yPosition + imgHeight > pageHeight - 20) {
        pdf.addPage()
        yPosition = 20
      }

      pdf.addImage(imgData, 'PNG', 20, yPosition, imgWidth, imgHeight)
      yPosition += imgHeight + 10
    } catch (error) {
      console.error('Failed to capture map:', error)
      addMapUnavailableCard(pdf, 20, yPosition, pageWidth - 40, 45, data.locationName)
      yPosition += 55
    }
  } else {
    addMapUnavailableCard(pdf, 20, yPosition, pageWidth - 40, 45, data.locationName)
    yPosition += 55
  }

  addFooter(pdf)

  // Download the PDF
  pdf.save(`${sanitizeFilenamePart(data.locationName)}_score_breakdown.pdf`)
}

export async function generateComparisonBrief(locations: CandidateLocation[], title = 'Location Comparison'): Promise<void> {
  const comparableLocations = locations.filter((location) => location.rawScores)
  if (comparableLocations.length === 0) return

  const pdf = new jsPDF('l', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  let yPosition = 18
  const weightKeys: Array<keyof RawScores> = ['wealth', 'family', 'education', 'competition', 'accessibility']
  const weightLabels: Record<keyof RawScores, string> = {
    wealth: 'Wealth',
    family: 'Family',
    education: 'Education',
    competition: 'Competition',
    accessibility: 'Accessibility',
  }

  pdf.setFillColor(236, 253, 245)
  pdf.rect(10, 10, pageWidth - 20, 24, 'F')
  pdf.setDrawColor(6, 95, 70)
  pdf.rect(10, 10, pageWidth - 20, 24)
  pdf.setTextColor(6, 95, 70)
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(20)
  pdf.text('theCoderSchool Market Lens', 15, yPosition)
  yPosition += 9
  pdf.setTextColor(15, 23, 42)
  pdf.setFontSize(14)
  pdf.text(title, 15, yPosition)
  yPosition += 14

  const factorColWidth = 42
  const valueColWidth = (pageWidth - 20 - factorColWidth) / comparableLocations.length

  pdf.setFillColor(241, 245, 249)
  pdf.rect(10, yPosition, pageWidth - 20, 12, 'F')
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Factor', 14, yPosition + 8)
  comparableLocations.forEach((location, index) => {
    const x = 10 + factorColWidth + index * valueColWidth
    const shortName = location.name.replace(/,\s*/g, ' ').slice(0, 26)
    pdf.text(shortName, x + 4, yPosition + 5)
    pdf.setFont('helvetica', 'normal')
    pdf.text(`Score: ${location.score}/100`, x + 4, yPosition + 9)
    pdf.setFont('helvetica', 'bold')
  })
  yPosition += 12

  const rows = [
    { label: 'Estimated Families', values: comparableLocations.map((location) => location.estimatedFamilies) },
    { label: 'Median Income', values: comparableLocations.map((location) => location.medianIncome) },
    { label: 'Competition', values: comparableLocations.map((location) => location.competition) },
    ...weightKeys.map((key) => ({
      label: weightLabels[key],
      values: comparableLocations.map((location) => `${location.rawScores?.[key].toFixed(1) ?? '0.0'}`),
    })),
  ]

  rows.forEach((row, rowIndex) => {
    const rowHeight = 10
    pdf.setFillColor(rowIndex % 2 === 0 ? 255 : 248, rowIndex % 2 === 0 ? 255 : 250, rowIndex % 2 === 0 ? 255 : 252)
    pdf.rect(10, yPosition, pageWidth - 20, rowHeight, 'F')
    pdf.setDrawColor(226, 232, 240)
    pdf.rect(10, yPosition, pageWidth - 20, rowHeight)
    pdf.setTextColor(15, 23, 42)
    pdf.setFont('helvetica', 'bold')
    pdf.text(row.label, 14, yPosition + 6.5)
    pdf.setFont('helvetica', 'normal')

    row.values.forEach((value, index) => {
      const x = 10 + factorColWidth + index * valueColWidth
      pdf.text(String(value), x + 4, yPosition + 6.5)
    })

    yPosition += rowHeight
  })

  yPosition += 8
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(12)
  pdf.text('Rationales', 15, yPosition)
  yPosition += 8
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(10)

  comparableLocations.forEach((location, index) => {
    const rationaleLines = pdf.splitTextToSize(
      `${index + 1}. ${location.name}: ${location.rationale}`,
      pageWidth - 30
    )
    if (yPosition + rationaleLines.length * 4 > 190) {
      addFooter(pdf)
      pdf.addPage()
      yPosition = 20
    }
    pdf.text(rationaleLines, 15, yPosition)
    yPosition += rationaleLines.length * 4 + 4
  })

  addFooter(pdf)
  pdf.save(`${sanitizeFilenamePart(title)}.pdf`)
}
